version: '3'
services:
  grafana:
    hostname: grafana
    command: 'entrypoint.sh'
    build: .
    ports:
      - '3000:3000'
    environment:
      - AWS_REGION=eu-central-1
      - GF_SERVER_ROOT_URL=https://${INFLUXDB_HOST}
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_NAME=${SITE_CODE}_grafana
      - GF_DATABASE_USER=${SITE_CODE}_grafana
      - GF_DATABASE_HOST=${RDS_HOST}
      - GF_DATABASE_PORT=3306
      - GF_DATABASE_PASSWORD=${PASS}
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Editor
      - GF_USERS_EDITORS_CAN_ADMIN=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ALERTING_ENABLED=true
      - GF_USERS_ALLOW_SIGN_UP=false
